CREATE TYPE relationship_type AS ENUM ('SPOUSE', 'COUPLE', 'SOME');
CREATE TYPE trial_visibility AS ENUM ('PUBLIC');
CREATE TYPE trial_status AS ENUM (
    'PREPARING', 'INTRODUCTION', 'A_ARGUMENT', 'B_ARGUMENT',
    'VOTING', 'VERDICT', 'ENDED'
);
CREATE TYPE trial_side AS ENUM ('A', 'B');
CREATE TYPE trial_speaker AS ENUM ('JUDGE', 'A_LAWYER', 'B_LAWYER', 'SYSTEM');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    demo_key VARCHAR(100) NOT NULL UNIQUE,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(150) NOT NULL,
    content TEXT NOT NULL,
    relationship_type relationship_type NOT NULL,
    trial_requested BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_posts_created_at ON posts(created_at);

CREATE TABLE trials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL UNIQUE REFERENCES posts(id),
    creator_id BIGINT NOT NULL REFERENCES users(id),
    visibility trial_visibility NOT NULL DEFAULT 'PUBLIC',
    status trial_status NOT NULL DEFAULT 'PREPARING',
    started_at TIMESTAMPTZ,
    phase_started_at TIMESTAMPTZ,
    phase_ends_at TIMESTAMPTZ,
    scheduled_end_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_trials_visibility_status ON trials(visibility, status);
CREATE INDEX idx_trials_scheduled_end_at ON trials(scheduled_end_at);

CREATE TABLE trial_parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id BIGINT NOT NULL REFERENCES trials(id) ON DELETE CASCADE,
    side trial_side NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    ready BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_trial_parties_trial_side UNIQUE (trial_id, side)
);

CREATE TABLE trial_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_party_id BIGINT NOT NULL UNIQUE REFERENCES trial_parties(id) ON DELETE CASCADE,
    incident_time VARCHAR(100) NOT NULL,
    situation TEXT NOT NULL,
    counterpart_action TEXT NOT NULL,
    own_action TEXT NOT NULL,
    after_conversation TEXT NOT NULL,
    desired_resolution TEXT NOT NULL,
    fact_summary TEXT,
    argument_text TEXT,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_guide_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_party_id BIGINT NOT NULL REFERENCES trial_parties(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    question VARCHAR(1000) NOT NULL,
    answer TEXT,
    answered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_guide_questions_party_sequence UNIQUE (trial_party_id, sequence_no)
);

CREATE TABLE trial_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id BIGINT NOT NULL REFERENCES trials(id) ON DELETE CASCADE,
    sequence_no BIGINT NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    speaker trial_speaker NOT NULL,
    content TEXT,
    payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_trial_events_trial_sequence UNIQUE (trial_id, sequence_no)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id BIGINT NOT NULL REFERENCES trials(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(id),
    sequence_no BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_chat_messages_trial_sequence UNIQUE (trial_id, sequence_no)
);
CREATE INDEX idx_chat_messages_trial_created_at ON chat_messages(trial_id, created_at);

CREATE TABLE votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id BIGINT NOT NULL REFERENCES trials(id) ON DELETE CASCADE,
    voter_id BIGINT NOT NULL REFERENCES users(id),
    selected_side trial_side NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_votes_trial_voter UNIQUE (trial_id, voter_id)
);

CREATE TABLE verdicts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trial_id BIGINT NOT NULL UNIQUE REFERENCES trials(id) ON DELETE CASCADE,
    winner_side trial_side NOT NULL,
    a_fault_ratio INTEGER NOT NULL,
    b_fault_ratio INTEGER NOT NULL,
    summary TEXT NOT NULL,
    grounds JSONB NOT NULL,
    a_recommendation TEXT NOT NULL,
    b_recommendation TEXT NOT NULL,
    prompt_version VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_verdict_a_ratio CHECK (a_fault_ratio BETWEEN 0 AND 100),
    CONSTRAINT chk_verdict_b_ratio CHECK (b_fault_ratio BETWEEN 0 AND 100),
    CONSTRAINT chk_verdict_ratio_sum CHECK (a_fault_ratio + b_fault_ratio = 100)
);
