export const TRIAL_EVENT_TYPE = Object.freeze({
  TRIAL_STARTED: 'TRIAL_STARTED',
  JUDGE_INTRODUCTION: 'JUDGE_INTRODUCTION',
  A_ARGUMENT: 'A_ARGUMENT',
  B_ARGUMENT: 'B_ARGUMENT',
  VOTING_STARTED: 'VOTING_STARTED',
  VERDICT_ANNOUNCED: 'VERDICT_ANNOUNCED',
  VERDICT_PUBLISHED: 'VERDICT_PUBLISHED',
  TRIAL_ENDED: 'TRIAL_ENDED',
})
