export const CONNECTION_STATUS = Object.freeze({ CONNECTING: 'CONNECTING', CONNECTED: 'CONNECTED', RECONNECTING: 'RECONNECTING', ERROR: 'ERROR' })
export const CHAT_STATUS = Object.freeze({ LOADING: 'LOADING', READY: 'READY', ERROR: 'ERROR', CLOSED: 'CLOSED' })
export const VOTE_STATUS = Object.freeze({ WAITING: 'WAITING', OPEN: 'OPEN', SUBMITTED: 'SUBMITTED' })
