export const TRIAL_EVENT_TYPE = Object.freeze({
  TRIAL_STARTED: 'TRIAL_STARTED', JUDGE_INTRODUCTION: 'JUDGE_INTRODUCTION', JUDGE_PHASE_NOTICE: 'JUDGE_PHASE_NOTICE', A_ARGUMENT: 'A_ARGUMENT',
  B_ARGUMENT: 'B_ARGUMENT', DEBATE_STARTED: 'DEBATE_STARTED', A_DEBATE: 'A_DEBATE', B_DEBATE: 'B_DEBATE',
  VOTING_OPENED: 'VOTING_OPENED', VOTING_STARTED: 'VOTING_STARTED', VERDICT_ANNOUNCED: 'VERDICT_ANNOUNCED',
  VERDICT_PUBLISHED: 'VERDICT_PUBLISHED', TRIAL_ENDED: 'TRIAL_ENDED',
  PRESENCE_UPDATED: 'PRESENCE_UPDATED',
})
